Update all testing dependencies.
The change to Repository.swift is needed for completion in Swift 5.3 beta.

The change to Fixtures.swift is to avoid this error:

```txt
Test Case '-[SwiftGit2_OSXTests.TreeSpec Tree_hashValue__should_be_equal_with_equal_objects]' started.
Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=4 "“F4341C11-58CC-4F99-920E-B2A902603BA6-91163-00002CD72E00B708” couldn’t be removed." UserInfo={NSUserStringVariant=(
    Remove
), NSFilePath=/var/folders/qc/nl_zbsmd7630s8x95k57mdqw0000gn/T/org.libgit2.SwiftGit2/F4341C11-58CC-4F99-920E-B2A902603BA6-91163-00002CD72E00B708, NSUnderlyingError=0x107d0f1d0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}: file /Users/karemorstol/Programming/Libraries/SwiftGit2/SwiftGit2Tests/Fixtures/Fixtures.swift, line 51
2020-05-12 14:59:47.008297+0200 xctest[91163:548842] Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=4 "“F4341C11-58CC-4F99-920E-B2A902603BA6-91163-00002CD72E00B708” couldn’t be removed." UserInfo={NSUserStringVariant=(
    Remove
), NSFilePath=/var/folders/qc/nl_zbsmd7630s8x95k57mdqw0000gn/T/org.libgit2.SwiftGit2/F4341C11-58CC-4F99-920E-B2A902603BA6-91163-00002CD72E00B708, NSUnderlyingError=0x107d0f1d0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}: file /Users/karemorstol/Programming/Libraries/SwiftGit2/SwiftGit2Tests/Fixtures/Fixtures.swift, line 51
```

I'm assuming we can ignore this error in the teardown.